name: create-docker-image-and-push-to-hub
run-name: Create Docker Image and Push to Hub
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t chinrust/iconserver .
